name: ToDo API GitHub Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: dotnet build
      - run: dotnet test
      
      - run: mkdir ${{github.workspace}}/output
      
      - name: generate bom
        run: | 
          dotnet tool install --global CycloneDX
          dotnet CycloneDX TodoApi.csproj --output output

      - run: ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'

      - uses: dependencytrack/gh-upload-sbom@master
        with:
          serverhostname: 'dependencytrack-apiserver.delightfulground-74553658.australiaeast.azurecontainerapps.io'
          apikey: ${{ secrets.SECRET_OWASP_DT_KEY }}
          projectname: todo-api
          projectversion: 'main'
          bomfilename: "./output/bom.xml"
          autocreate: 'true'